<?php

// config/properties_inputs.php

// Genera automáticamente el array de niveles
$levels = [
    '-3' => 'Sotano 3',
    '-2' => 'Sotano 2',
    '-1' => 'Sotano 1',
    '0'  => 'Planta baja',
];

for ($i = 1; $i <= 99; $i++) {
    $levels[(string) $i] = "Nivel {$i}";
}

return [
    // Múltiples listas de inputs en un solo archivo
    'levels' => $levels,
    'property_types' => [
        '0' => 'Casa habitacion',
        '1'  => 'Casa habitacion en condominio',
        '2'  => 'Casas múltiples',
        '3'  => 'Departamento en condominio',
        '4'  => 'Edificio de productos',
        '5'  => 'Local comercial (aislado)',
        '6'  => 'Nave industrial',
        '7'  => 'Oficina',
        '8'  => 'Oficina en condominio',
        '9'  => 'Otro en construccion',
        '10'  => 'Terreno',
        '11'  => 'Terreno en condominio',
        '12'  => 'Vivienda recuperada'
    ],
    'property_types_sigapred' => [
        '0' => 'Bodega',
        '1' => 'Cajón de estacionamiento',
        '2' => 'Casa habitacion',
        '3' => 'Casa habitacion condominio',
        '4' => 'Centro comercial',
        '5' => 'Departamento en condominio',
        '6' => 'Edificio de departamentos',
        '7' => 'Edificio de estacionamiento',
        '8' => 'Edificio de productos',
        '9' => 'Escuela',
        '10' => 'Hospital',
        '11' => 'Hotel',
        '12' => 'Local comercial',
        '13' => 'Nave industrial',
        '14' => 'Oficina aislada',
        '15' => 'Oficina en condominio',
        '16' => 'Terreno con uso comercial',
        '17' => 'Terreno habitacional',
        '18' => 'Otro',
    ],
    'land_use' => [
        '0' => 'Bodega o cuarto de servicio',
        '1' => 'Comercio',
        '2' => 'Cultura',
        '3' => 'Deporte',
        '4' => 'Educación',
        '5' => 'Estacionamiento',
        '6' => 'Habitacional',
        '7' => 'Hotel',
        '8' => 'Industria',
        '9' => 'Oficina',
        '10' => 'Salud',
    ],
    'zone_classification' => [
        '0' => '1. Habitacional de lujo',
        '1' => '2. Habitacional de primer orden',
        '2' => '3. Habitacional de segundo orden',
        '3' => '4. Habitacional de tercer orden',
        '4' => '5. Habitacional de interés social',
        '5' => '6. Habitacional de popular',
        '6' => '7. Habitacional de campestre',
        '7' => '8. Comercial de lujo',
        '8' => '9. Comercial de primer orden',
        '9' => '11. Comercial de segundo orden',
        '10' => '11. Comercial de tercer orden',
        '11' => '12. Industrial',
        '12' => '13. Mixta habitacional y comercial',
        '13' => '14. Mixta industrial y comercial',
        '14' => '15. Mixta habitacional e industrial vecina',
        '15' => '16. Mixta habitacional y servicios',
        '16' => '17. Mixta industrial y servicios',
        '17' => '18. Agricola',
        '18' => '19. Ganadera',
        '19' => '20. Agricola y ganadera'
    ],
    'zone_saturation_index' => [
        '0' => 100,
        '1' => 95,
        '2' => 90,
        '3' => 85,
        '4' => 80,
        '5' => 75,
        '6' => 70,
        '7' => 65,
        '8' => 60,
        '9' => 55,
        '10' => 50,
        '11' => 45,
        '12' => 40,
        '13' => 35,
        '14' => 30,
        '15' => 25,
        '16' => 20,
        '17' => 15,
        '18' => 10,
    ],
    'proximity_urban_reference' => [
        ['clave' => '1', 'nombre' => 'Centrica', 'descripcion' => 'Zonas limitadas generalmente por vía primarias, definidas por la autoridad como zona centro'],
        ['clave' => '2', 'nombre' => 'Intermedia',   'descripcion' => 'Se trata de una proximidad definida a partir de vias primarias limitadas generalmente por vialidades de velocidad intermedia'],
        ['clave' => '3', 'nombre' => 'Periférica',    'descripcion' => 'Se encuentra su acceso y límite mediante vías rápidas, en la mayoria de los casos reconocida como zona urbana de crecimiento inmediato, forma parte de la ciudad'],
        ['clave' => '4', 'nombre' => 'De expansión',  'descripcion' => 'Zona reconocida por la autoridad como de crecimiento potencial, en muchos casos no se encuentra definido su uso de suelo y se encuentra en proceso de reconomcimiento, en función de su crecimiento, próxima a ser parte de la ciudad'],
        ['clave' => '5', 'nombre' => 'Rural',         'descripcion' => 'Reconocido por la autoridad como de uso agrícola o sin dotación de servicios'],
    ],
    'construction_classification' => [
        '0' => 'Minima',
        '1' => 'Economica',
        '2' => 'Interes social',
        '3' => 'Media',
        '4' => 'Semilujo',
        '5' => 'Residencial',
        '6' => 'Residencial plus',
        '7' => 'Residencial plus +',
        '8' => 'Unica'
    ],
    'construction_use' => [
        'A' => 'Abasto (bodega o cuarto de servicio)',
        'C' => 'Comercio',
        'D' => 'Deporte',
        'E' => 'Educacion',
        'F' => 'Educacion',
        'H' => 'Habitacional',
        'I' => 'Industria',
        'J' => 'Jardines',
        'K' => 'Comunicaciones',
        'L' => 'Hotel',
        'O' => 'Oficina',
        'P' => 'Panteones',
        'PC' => 'Canchas deportivas',
        'PE' => 'Estacionamiento, patios y plazuelas',
        'Q' => 'Cultura',
        'S' => 'Salud',
        'W' => 'Baldio',
        'X' => 'Agricola'
    ],
    'construction_source_information' => [
        '0' => 'Escrituras',
        '1' => 'Datos proporcionados',
        '2' => 'Medicion (acorde al alcance)',
        '3' => 'Planos proporcionados',
        '4' => 'Regimen de condominio',
        '5' => 'Titulo de propiedad',
        '6' => 'Contrato de compra-venta',
        '7' => 'Calculos de perito valuador',
        '8' => 'Boleta predial',
    ],

    'construction_conservation_state' => [
        '0' => '0. Ruinoso',
        '1' => '0.8 Malo',
        '2' => '1. Normal',
        '3' => '1. Bueno',
        '4' => '1.1 Muy bueno',
        '5' => '1. Nuevo',
        '6' => '1.1 Recientemente remodelado',
    ],
    //Valores para la vida útil de los elementos
    'construction_life_values' => [

        'Minima_H' => 40,
        'Economica_H' => 60,
        'Interes social_H' => 60,
        'Media_H' => 70,
        'Semilujo_H' => 80,
        'Residencial_H' => 90,
        'Residencial plus_H' => 90,
        'Residencial plus +_H' => 90,
        'Unica_H' => 0,


        'Minima_C' => 40,
        'Economica_C' => 60,
        'Interes social_C' => 60,
        'Media_C' => 70,
        'Semilujo_C' => 80,
        'Residencial_C' => 90,
        'Residencial plus_C' => 90,
        'Residencial plus +_C' => 90,
        'Unica_C' => 0,

        'Minima_D' => 40,
        'Economica_D' => 60,
        'Interes social_D' => 60,
        'Media_D' => 70,
        'Semilujo_D' => 80,
        'Residencial_D' => 90,
        'Residencial plus_D' => 90,
        'Residencial plus +_D' => 90,
        'Unica_D' => 0,

        'Minima_E' => 40,
        'Economica_E' => 60,
        'Interes social_E' => 60,
        'Media_E' => 70,
        'Semilujo_E' => 80,
        'Residencial_E' => 90,
        'Residencial plus_E' => 90,
        'Residencial plus +_E' => 90,
        'Unica_E' => 0,

        'Minima_F' => 40,
        'Economica_F' => 60,
        'Interes social_F' => 60,
        'Media_F' => 70,
        'Semilujo_F' => 80,
        'Residencial_F' => 90,
        'Residencial plus_F' => 90,
        'Residencial plus +_F' => 90,
        'Unica_F' => 0,

        'Minima_I' => 40,
        'Economica_I' => 60,
        'Interes social_I' => 60,
        'Media_I' => 70,
        'Semilujo_I' => 80,
        'Residencial_I' => 90,
        'Residencial plus_I' => 90,
        'Residencial plus +_I' => 90,
        'Unica_I' => 0,

        'Minima_J' => 40,
        'Economica_J' => 60,
        'Interes social_J' => 60,
        'Media_J' => 70,
        'Semilujo_J' => 80,
        'Residencial_J' => 90,
        'Residencial plus_J' => 90,
        'Residencial plus +_J' => 90,
        'Unica_J' => 0,

        'Minima_K' => 40,
        'Economica_K' => 60,
        'Interes social_K' => 60,
        'Media_K' => 70,
        'Semilujo_K' => 80,
        'Residencial_K' => 90,
        'Residencial plus_K' => 90,
        'Residencial plus +_K' => 90,
        'Unica_K' => 0,

        'Minima_L' => 40,
        'Economica_L' => 60,
        'Interes social_L' => 60,
        'Media_L' => 70,
        'Semilujo_L' => 80,
        'Residencial_L' => 90,
        'Residencial plus_L' => 90,
        'Residencial plus +_L' => 90,
        'Unica_L' => 0,

        'Minima_O' => 40,
        'Economica_O' => 60,
        'Interes social_O' => 60,
        'Media_O' => 70,
        'Semilujo_O' => 80,
        'Residencial_O' => 90,
        'Residencial plus_O' => 90,
        'Residencial plus +_O' => 90,
        'Unica_O' => 0,

        'Minima_P' => 40,
        'Economica_P' => 60,
        'Interes social_P' => 60,
        'Media_P' => 70,
        'Semilujo_P' => 80,
        'Residencial_P' => 90,
        'Residencial plus_P' => 90,
        'Residencial plus +_P' => 90,
        'Unica_P' => 0,

        'Minima_PC' => 40,
        'Economica_PC' => 60,
        'Interes social_PC' => 60,
        'Media_PC' => 70,
        'Semilujo_PC' => 80,
        'Residencial_PC' => 90,
        'Residencial plus_PC' => 90,
        'Residencial plus +_PC' => 90,
        'Unica_PC' => 0,

        'Minima_PE' => 40,
        'Economica_PE' => 60,
        'Interes social_PE' => 60,
        'Media_PE' => 70,
        'Semilujo_PE' => 80,
        'Residencial_PE' => 90,
        'Residencial plus_PE' => 90,
        'Residencial plus +_PE' => 90,
        'Unica_PE' => 0,

        'Minima_Q' => 40,
        'Economica_Q' => 60,
        'Interes social_Q' => 60,
        'Media_Q' => 70,
        'Semilujo_Q' => 80,
        'Residencial_Q' => 90,
        'Residencial plus_Q' => 90,
        'Residencial plus +_Q' => 90,
        'Unica_Q' => 0,

        'Minima_S' => 40,
        'Economica_S' => 60,
        'Interes social_S' => 60,
        'Media_S' => 70,
        'Semilujo_S' => 80,
        'Residencial_S' => 90,
        'Residencial plus_S' => 90,
        'Residencial plus +_S' => 90,
        'Unica_S' => 0,

        'Minima_W' => 40,
        'Economica_W' => 60,
        'Interes social_W' => 60,
        'Media_W' => 70,
        'Semilujo_W' => 80,
        'Residencial_W' => 90,
        'Residencial plus_W' => 90,
        'Residencial plus +_W' => 90,
        'Unica_W' => 0,

        'Minima_X' => 40,
        'Economica_X' => 60,
        'Interes social_X' => 60,
        'Media_X' => 70,
        'Semilujo_X' => 80,
        'Residencial_X' => 90,
        'Residencial plus_X' => 90,
        'Residencial plus +_X' => 90,
        'Unica_X' => 0,
    ],




    //Valores para instalaciones especiales
    'special_installations' => [
        ['clave' => 'IE10', 'descripcion' => 'Antena parabólica'],
        ['clave' => 'IE12', 'descripcion' => 'Bóvedas de seguridad movibles'],
        ['clave' => 'IE18', 'descripcion' => 'Caldera'],
        ['clave' => 'IE09', 'descripcion' => 'Calefación'],
        ['clave' => 'IE01', 'descripcion' => 'Elevadores'],
        ['clave' => 'IE05', 'descripcion' => 'Equipo de lavado'],
        ['clave' => 'IE16', 'descripcion' => 'Equipo contra incendios'],
        ['clave' => 'IE04', 'descripcion' => 'Equipos de aire acondicionado'],
        ['clave' => 'IE17', 'descripcion' => 'Equipos de seguridad y CCTV'],
        ['clave' => 'IE03', 'descripcion' => 'Escaleras electromecánicas'],
        ['clave' => 'IE02', 'descripcion' => 'Montacargas'],
        ['clave' => 'IE19', 'descripcion' => 'Otros'],
        ['clave' => 'IE15', 'descripcion' => 'Pararrayos'],
        ['clave' => 'IE07', 'descripcion' => 'Riesgo por asperción'],
        ['clave' => 'IE08', 'descripcion' => 'Sistema de sonido ambiental'],
        ['clave' => 'IE06', 'descripcion' => 'Sistema hidroneumático'],
        ['clave' => 'IE11', 'descripcion' => 'Sistema de aspiración central'],
        ['clave' => 'IE14', 'descripcion' => 'Sistemas de intercomunicación (interfón, portero eléctrico'],
        ['clave' => 'IE13', 'descripcion' => 'Subestación eléctrica'],
    ],
    'elements_accessories' => [
        ['clave' => 'EA08', 'descripcion' => 'Antena maestra de TV y FM'],
        ['clave' => 'EA05', 'descripcion' => 'Butacas'],
        ['clave' => 'EA06', 'descripcion' => 'Cámaras frigoríficas movibles'],
        ['clave' => 'EA09', 'descripcion' => 'Cocinas integrales movibles'],
        ['clave' => 'EA02', 'descripcion' => 'Depósito de combustible'],
        ['clave' => 'EA10', 'descripcion' => 'Equipos de bombeo'],
        ['clave' => 'EA11', 'descripcion' => 'Gas estacionario'],
        ['clave' => 'EA01', 'descripcion' => 'Horno industrial'],
        ['clave' => 'EA12', 'descripcion' => 'Otros'],
        ['clave' => 'EA03', 'descripcion' => 'Pantalla cinematográfica'],
        ['clave' => 'EA04', 'descripcion' => 'Planta de luz de emergencia'],
        ['clave' => 'EA07', 'descripcion' => 'Portones de operación electrica'],
    ],
    'complementary_works' => [
        ['clave' => 'OC11', 'descripcion' => 'Alberas y chapoteadores'],
        ['clave' => 'OC01', 'descripcion' => 'Bardas, celosías'],
        ['clave' => 'OC13', 'descripcion' => 'Bóvedas de seguridas hechas en obra'],
        ['clave' => 'OC16', 'descripcion' => 'Cámaras frigopríficas hechas en obra'],
        ['clave' => 'OC10', 'descripcion' => 'Cisternas o aljibes'],
        ['clave' => 'OC09', 'descripcion' => 'Cocinas integrales hechas en obra'],
        ['clave' => 'OC18', 'descripcion' => 'Costo de cura'],
        ['clave' => 'OC15', 'descripcion' => 'Espuela de ferrocarril en industrias'],
        ['clave' => 'OC07', 'descripcion' => 'Fuente y espejos de agua'],
        ['clave' => 'OC14', 'descripcion' => 'Horno industrial hecho en obra'],
        ['clave' => 'OC06', 'descripcion' => 'Jardines'],
        ['clave' => 'OC04', 'descripcion' => 'Marquesinas'],
        ['clave' => 'OC17', 'descripcion' => 'Otros'],
        ['clave' => 'OC03', 'descripcion' => 'Patios y andadores'],
        ['clave' => 'OC05', 'descripcion' => 'Pérgolas'],
        ['clave' => 'OC12', 'descripcion' => 'Pozos artesianos'],
        ['clave' => 'OC02', 'descripcion' => 'Rejas'],
        ['clave' => 'OC08', 'descripcion' => 'Terrazas y balcones'],
    ],
    'special_installations_unit' => [
        '0' => 'Pieza',
        '1' => 'M2',
        '2' => 'M3',
        '3' => 'ML',
        '4' => 'LTS',
        '5' => 'Lote',
    ],
    'special_installations_conservationFactor' => [
        ['clave' => '1', 'nombre' => 'Ruinoso','factor' => '0.0'],
        ['clave' => '2', 'nombre' => 'Malo','factor' => '0.8'],
        ['clave' => '3', 'nombre' => 'Normal','factor' => '1.0'],
        ['clave' => '4', 'nombre' => 'Bueno','factor' => '1.0'],
        ['clave' => '5', 'nombre' => 'Muy bueno','factor' => '1.1'],
        ['clave' => '6', 'nombre' => 'Nuevo','factor' => '1.0'],
        ['clave' => '7', 'nombre' => 'Recientemente remodelado','factor' => '1.1'],
    ],
];
